openapi: 3.0.3
info:
  title: Email
  contact:
    name: CIP Insights & Reputation Team
    email: cip-insights-and-reputation-g@digital.hmrc.gov.uk
  version: '1.0'
  description: >
    # Overview
    ### Email Verification
    This API validates a user's email by sending a verification code, which the user enters to complete the verification.

servers:
  - url: https://test-api.service.hmrc.gov.uk/misc/email
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/misc/email
    description: Production
paths:
  /send-code:
    post:
      summary: Send a verification code to the provided email
      description: >
        Generate a unique verification code and send it to the email provided.
      operationId: SendEmailVerificationCode
      security:
        - applicationRestricted: [ ]
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/send-code-request.json'
            example:
              email: "joe@bloggs.co.uk"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/send-code-response.json'
              example:
                status: 'CODE_SENT'
                message: 'Email containing verification code has been sent'
        3XX:
          description: |
            The request has been redirected. Clients should follow the redirect using the location header as per the HTTP specification.
        400:
          description: |
            The request was invalid, e.g Invalid Email.
        5XX:
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.
      deprecated: false
  /verify-code:
    post:
      summary: Verify an email verification code
      description: >
        Verify the verification code sent to this email matches.
      operationId: CheckEmailVerificationCode
      security:
        - applicationRestricted: [ ]
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/verify-code-request.json'
            example:
              email: "joe@bloggs.co.uk"
              verificationCode: "GTNFVP"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/verify-code-response.json'
              example:
                status: 'CODE_VERIFIED'
                message: 'The verification code for the email verified successfully'
        3XX:
          description: |
            The request has been redirected. Clients should follow the redirect using the location header as per the HTTP specification.
        400:
          description: |
            The request was invalid, e.g Invalid Email.
        5XX:
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.
      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json",
          "application/vnd.hmrc.1.0+xml"
        ]
      required: true
